### PR TITLE
Fixing cross-section-to-netcdf script

### PR DESCRIPTION
**Pull request by thijsheus**
The script now runs again. Fixes https://github.com/microhh/microhh/issues/147
No changes in chunking yet

### CODE REVIEW

**Comment by julietbravo** [comment]
I'm still having issues here:

```
                 halflevel = '000'
                 if not at_surface:
                     if indexes is None:
                         indexes_local,halflevel = mht.get_cross_indices(variable, mode)
                     else:
                         indexes_local = indexes
```

If you specify the `indexes`, then halflevel is always `000`, and cross-sections of e.g. `u` fail.

This seems to work in my test:
```

                if not at_surface:
                    if indexes is None:
                        indexes_local, halflevel = mht.get_cross_indices(variable, mode)
                    else:
                        indexes_local = indexes

                        files = glob.glob("{0:}.{1}.*.{2:05d}.{3:07d}".format(
                                variable, mode, indexes_local[0], starttime))
                        if len(files) == 0:
                            raise Exception('Cannot find any cross-section')
                        halflevel = files[0].split('.')[-3]
```

**Comment by julietbravo** [comment]
I made a PR in your fork @thijsheus  with the proposed fix.

**Review by julietbravo — APPROVED** [review]
Just tested it, works for me!

**Comment by WBMol** [comment]
Works here too, thanks!

image

**Pull request merged**
