### PR TITLE
add a RICO case adapted for coupled radiative transfer

### PR DESCRIPTION
**Pull request by MennoVeerman**
As requested

### CODE REVIEW

**Comment by MennoVeerman** [comment]
I adapted the rico_input.nc file, not the rico_input.py, hence why I uploaded that version. If preferred, I will create a rico_radiation_input.py, but that may take a bit longer then.

**Comment by julietbravo** [comment]
I think that would be nice; we have that with all our cases, and it allows users to change the resolution, settings, ....

**Comment by MennoVeerman** [comment]
I changed the files, hopefully this is better

**Comment by julietbravo** [comment]
Looks good to me, thanks!

**Comment by thijsheus** [comment]
Looks good!

**Pull request merged**
