### PR TITLE
Convert some cases to Xarray

### PR DESCRIPTION
**Pull request by bartvstratum**
Start at converting some cases from `netCDF4` to `xarray`. As a test, I ported the `moser180` statistics to a Python notebook. Advantage is that you can see the figures online in Github, disadvantage is that all images are included in the Git repository. 

Example:
https://github.com/bartvstratum/microhh/blob/develop_moser/cases/moser180/moser180_stats.ipynb

What do you think about the notebooks: aye or nay?

### CODE REVIEW

**Comment by Chiil** [comment]
I like the notebooks, it is a nice idea to combine also some explanation to the test cases for new users.

**Comment by bartvstratum** [comment]
The `moser180` notebook is 1.2 MB, which is indeed quite large. But for me personally, 98% of the advantage of a notebook is the ability to display the images on Github, without having to run the case.

One disadvantage of notebooks is that you can't easily edit them with e.g. `vi` when you are on a supercomputer. I guess the same is true for running them without a browser (?). If we don't include the images in the repository, then I personally would probably prefer to stick to "dumb" Python scripts, since you can easily edit/run them everywhere.

**Comment by bartvstratum** [comment]
An alternative is to create a dedicated repository for the Notebooks. You could link to that from each case README, and if some external repository grows a bit big, that's less of a concern to me...

**Comment by bartvstratum** [comment]
I'm starting to agree that the notebooks should be without output, they indeed grow quickly in size. 

It is possible to check if notebooks contain output using an automatic `pre-commit` check:

```
(venvs) bart@eddy:~/meteo/models/microhh$ git commit -a
ERROR: notebook cases/taylorgreen/taylorgreen_plot.ipynb contains output cells!
Use 'Kernel -> Restart & Clear Output' to clear them.
```

Probably good to include that, to prevent users from accidentally committing notebooks with output.

I will manually copy the `moser180` notebooks to a new branch and open a new pull request, to get rid of the figures in git history.

**Comment by bartvstratum** [comment]
Replaced by: https://github.com/microhh/microhh/pull/298

**Pull request closed without merging**
