### PR TITLE
Deardorff TKE scheme

### PR DESCRIPTION
**Pull request by julietbravo**
@StevenvdLinden 's implementation of the TKE scheme.

I quite thoroughly tested this in `main`;
- code compiles for CPU/GPU/SP/DP/MPI.
- Code runs stable now for a variety of unstable/stable/neutral cases (see below). NOTE: I did the majority of testing with `swadvec=2i5` and `fluxlimit_list=sgstke`. 
- The new TKE scheme is included in `run_restart_set.py` for `drycblles` and `bomex`; all pass on Eddy (CPU/GPU/SP/DP/MPI).

The latest `main` is merged in. Most changes are in (_duhh_) the new `diff_tke2` files. Also `diff_smag2` changed a lot, since many of the kernels which are the same in `smag2` and `tke2` are now in a shared header.

## Discussion point(s):
- This version limits `sgstke` at `sgstke_min` for a cold start. Otherwise the code blows up instantly if users forget to specify a reasonable initial value in their input files. Do we want this, of is that up to the user to specify the initial subgrid TKE? We could make `sgstke` mandatory (i.e. not let it default at 0.0 if it is missing in the `case_input.nc`)?

## test cases
All plots are time averages over at least a few hours. `drycblles` is the version with an initial BL depth of 1000m, and a strong inversion, to make it somewhat steady state for averaging.

### `drycblles`
ddrycblles_tke
drycblles_evisc_th

### `bomex`
bomex_tke
bomex_evisc

### `gabls1`
gabls1_tke
gabls1_evisc_th

### CODE REVIEW

**Comment by thijsheus** [comment]
Overall this looks like great work to me. I have two questions:
1) Regarding the minimum value: 
- Can we imagine a situation where 1e-7 is too large? If so, it should (also) be in the .ini file. This could easily be added later though, if necessary.
- I am not quite convinced yet about putting this merely in the `init` mode. If TKE<=TKE_MIN leads to crashes, we should check for that every time step, and therefore it should be part of every time step, not just the create routine

2) Less seriously, but I wanted to have it asked: SFS or SGS?

**Comment by julietbravo** [comment]
I had some issues with `sgstke_min` smaller than `1e-7`, but that could have also been caused by the bug in the limiter. DALES uses a slightly smaller number (5e-5 for `sqrt(sgstke)`). 

The limiter ensures that `sgstke` stays larger than `sgstke_min`, so another check should not be necessary. I also think that the goal of the limiter was to handle these limitations through the tendencies, and not do things like `sgstke[ijk] = std::max(sgstke[ijk], sgstke_min)`. If we do want to hard limit `sgstke`, we could do it locally in kernels, without changing the prognostic field?

Deardorff himself (1980) used _"E is the subgrid-scale turbulence energy.."_. So did Smagorinsky. I would use "subfilter-scale" when you use an explicit filter (like e.g. in a dynamic Smagorinsky model), but since we don't do that, I am personally fine with sticking to `sgstke`.

**Comment by Chiil** [comment]
1. The limiter should be able to handle it properly, I guess. I just made a bad limiter but that should have been fixed with Bart's edits.
2. Sullivan and Moeng also call their TKE scheme SGS.

**Review by thijsheus — APPROVED** [review]
Look's good to me!

**Pull request merged**
