### PR TITLE
Update main `README.md`

### PR DESCRIPTION
**Pull request by julietbravo**

### CODE REVIEW

**Comment by thijsheus** [comment]
Should we make generic.cmake the standard version instead of the random ubuntu.cmake?

For instance:
Assuming your LIBRARY_PATH and INCLUDE_PATH are set correctly, `generic.cmake` is a good starting point, and may work without (much) modification
cp generic.cmake default.cmake
....

**Comment by julietbravo** [comment]
Yes, good point. Haven't tried `generic.cmake` yet, but I will try to incorporate it in the README.

**Comment by Chiil** [comment]
Shall we move the contributing section to a new file `CONTRIBUTING.md`? And if we want to list who contributed what to the code in a `.md` file, shall we create a new one then?

**Comment by thijsheus** [comment]
Looks good to me!

**Pull request merged**
